{
 "title": "KSB Monitoring",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "resolution",
    "query": "1m,5m,10m,15m,30m,1h,2h,3h,6h,12h,1d,2d,3d,7d,14d,30d"
   },
   { "name": "show_balances", "query": "USD : 2, SDR : 1, Hide : 0" },
   {
    "name": "wallet_filter",
    "query": {
     "query": "label_values(sd_balance_by_wallet_gauge, wallet)"
    }
   },
   {
    "name": "resolution_s",
    "query": {
     "query": "query_result(label_replace(label_replace(label_replace(label_replace(vector(1),\"resolution_s\",\"${resolution}\",\"\",\"\"),\"resolution_s\",\"(60*$1)\",\"resolution_s\",\"([0-9]+)m\"),\"resolution_s\",\"(3600*$1)\",\"resolution_s\",\"([0-9]+)h\"),\"resolution_s\",\"(86400*$1)\",\"resolution_s\",\"([0-9]+)d\"))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Connected Workers",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(last_over_time(sd_valid_share_counter{wallet=~\"${wallet_filter}\"}[1m]) - last_over_time(sd_valid_share_counter{wallet=~\"${wallet_filter}\"}[1m] offset 10m)) by (worker) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Hashrates (1m, 1h, 1d)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Hs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(rate(sd_valid_share_diff_counter{wallet=~\"${wallet_filter}\"}[1m]))  * 1e9",
     "legendFormat": "1m"
    },
    {
     "expr": "SUM(rate(sd_valid_share_diff_counter{wallet=~\"${wallet_filter}\"}[1h])) * 1e9",
     "legendFormat": "1h"
    },
    {
     "expr": "SUM(rate(sd_valid_share_diff_counter{wallet=~\"${wallet_filter}\"}[1d])) * 1e9",
     "legendFormat": "1d"
    }
   ]
  },
  {
   "title": "Balance Change",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(sd_balance_by_wallet_gauge{wallet=~\"${wallet_filter}\"}[${resolution}]) * scalar((coin_price{currency=\"sdr\"} * on() vector(${show_balances} == bool 2)) + (${show_balances} * (${show_balances} < bool 2)))",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "Total Balance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM (sd_balance_by_wallet_gauge{wallet=~\"${wallet_filter}\"}) * scalar((coin_price{currency=\"sdr\"} * on() vector(${show_balances} == bool 2)) + (${show_balances} * (${show_balances} < bool 2)))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "SDR Price",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "coin_price{currency=\"sdr\"}",
     "legendFormat": "USD/SDR"
    }
   ]
  },
  {
   "title": "Blocks Mined",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(increase(sd_blocks_mined{wallet=~\"${wallet_filter}\"}[${resolution}]))",
     "legendFormat": "Blocks"
    }
   ]
  },
  {
   "title": "Time Since Last Block",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max_over_time(timestamp(sum(changes(sd_blocks_mined{wallet=~\"${wallet_filter}\"}[5m]) > 0))[1d:1m]) + 300",
     "legendFormat": "Elapsed time"
    }
   ]
  },
  {
   "title": "Est. Time per Block",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(sd_estimated_network_hashrate_gauge) / (sum(rate(sd_valid_share_diff_counter{wallet=~\"${wallet_filter}\"}[${resolution}])) * 1e9)) / 60",
     "legendFormat": "Block time"
    }
   ]
  },
  {
   "title": "Network Hashrate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Hs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sd_estimated_network_hashrate_gauge",
     "legendFormat": "Nethash"
    }
   ]
  },
  {
   "title": "Network Difficulty",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "K" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " avg(sd_network_difficulty_gauge) / 1000000000000",
     "legendFormat": "Netdiff"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "MAX(sd_network_block_count)", "legendFormat": "Block Height" }
   ]
  },
  {
   "title": "Blocks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "${resolution_s} * 1e9 * sum(rate(sd_valid_share_diff_counter{wallet=~\"${wallet_filter}\"}[${resolution}])) / avg(sd_estimated_network_hashrate_gauge)",
     "legendFormat": "Blocks (expected)"
    },
    {
     "expr": "sum(increase(sd_blocks_mined{wallet=~\"${wallet_filter}\"}[${resolution}]))",
     "legendFormat": "Blocks (actual)"
    },
    {
     "expr": "sum(sd_blocks_mined{wallet=~\"${wallet_filter}\"} - sd_blocks_mined{wallet=~\"${wallet_filter}\"} offset $__interval > 0) by (worker)",
     "legendFormat": "{{worker}}"
    }
   ]
  },
  {
   "title": "Participation by Blocks",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "blocks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(sd_blocks_mined{wallet=~\"${wallet_filter}\"}[$resolution])) by (worker)",
     "legendFormat": "{{worker}}"
    }
   ]
  },
  {
   "title": "Participation by Shares",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "shares" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(sd_valid_share_diff_counter{wallet=~\"${wallet_filter}\"}[$resolution])) by (worker)",
     "legendFormat": "{{worker}}"
    }
   ]
  },
  {
   "title": "Hashrate by Worker",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "GHs" } },
   "targets": [
    {
     "expr": "SUM(rate(sd_valid_share_diff_counter{wallet=~\"${wallet_filter}\"}[$resolution]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(sd_valid_share_diff_counter{wallet=~\"${wallet_filter}\"}[$resolution])) by (worker)",
     "legendFormat": "{{worker}}"
    }
   ]
  },
  {
   "title": "Shares per Minute",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(sd_valid_share_counter{wallet=~\"${wallet_filter}\"}[$resolution]) * 60) by (worker)",
     "legendFormat": "{{worker}}"
    }
   ]
  },
  {
   "title": "Hashrate by Miner",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "GHs" } },
   "targets": [
    {
     "expr": "SUM BY (miner) (rate(sd_valid_share_diff_counter{wallet=~\"${wallet_filter}\"}[$resolution]))",
     "legendFormat": "{{miner}}"
    }
   ]
  },
  {
   "title": "Rejected Shares",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "SUM BY(worker, type) (rate(sd_invalid_share_counter{wallet=~\"${wallet_filter}\"}[${resolution}]))",
     "legendFormat": "{{worker}} : {{type}}"
    },
    {
     "expr": "increase(sd_invalid_share_counter{wallet=~\"${wallet_filter}\"}[$__interval])",
     "legendFormat": "{{worker}} : {{type}}"
    }
   ]
  },
  {
   "title": "Network Stats",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "Hs" } },
   "targets": [
    {
     "expr": "sd_estimated_network_hashrate_gauge",
     "legendFormat": "hashrate"
    },
    {
     "expr": "sd_network_difficulty_gauge / 1e12",
     "legendFormat": "difficulty"
    }
   ]
  },
  {
   "title": "Wallet Balances",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "AVG BY(wallet) (sd_balance_by_wallet_gauge{wallet=~\"${wallet_filter}\"}) *  ${show_balances}",
     "legendFormat": "{{wallet}}"
    }
   ]
  },
  {
   "title": "Network Block Rate",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "blocks/s" } },
   "targets": [
    {
     "expr": "SUM(delta(sd_network_block_count[1m])) / 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Estimated Time per Block",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum(sd_estimated_network_hashrate_gauge) / (sum(rate(sd_valid_share_diff_counter{wallet=~\"${wallet_filter}\"}[${resolution}])) * 1e9))",
     "legendFormat": "Estimate"
    }
   ]
  }
 ]
}